### ISSUE TITLE
Could not build on IOS 

### ISSUE THREAD

**Issue by hasnentai** [bdero/flutter-scene-example#1]
### Not able to run the repo because of the following error 

```
Error (Xcode): ../.pub-cache/hosted/pub.dev/flutter_scene-0.0.1-dev.1/lib/scene.dart:13:8: Error: Type 'ui.SceneNode' not found.
```

Flutter Doctor 
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 12.5 21G72 darwin-arm64, locale
    en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.79.2)
[✓] VS Code (version 1.71.0)
[✓] Connected device (3 available)            
[✓] Network resources

• No issues found!
```

**Comment by bdero** [comment]
The Flutter Scene [package](https://github.com/bdero/flutter_scene) currently requires a custom build of Flutter Engine to use (instructions here: https://github.com/flutter/flutter/wiki/Impeller-Scene).

After the [migration to Flutter GPU](https://github.com/bdero/flutter_scene/issues/1) is done, a custom engine build will no longer be required.

**Comment by KavehKavandi** [comment]
> The Flutter Scene [package](https://github.com/bdero/flutter_scene) currently requires a custom build of Flutter Engine to use (instructions here: https://github.com/flutter/flutter/wiki/Impeller-Scene).
> 
> After the [migration to Flutter GPU](https://github.com/bdero/flutter_scene/issues/1) is done, a custom engine build will no longer be required.

Hi Brandon,
I'm highly interested in using SceneBox for 3D rendering on Android within Flutter applications. I'm a relatively new Flutter developer, but I have a specific need to render PDB files (3D protein structures) on the fly.
Would you be able to provide a rough estimate on when SceneBox might gain Android support?
Thanks for your time and consideration!
