### ISSUE TITLE
Some classes from dart:ui Undefined issue

### ISSUE THREAD

**Issue by KavehKavandi** [bdero/flutter-scene-example#4]
Undefined SceneNode, SceneShader and SceneNodeValue classes in dart.ui

**Comment by bdero** [comment]
The Flutter Scene [package](https://github.com/bdero/flutter_scene) currently requires a custom build of Flutter Engine to use (instructions here: https://github.com/flutter/flutter/wiki/Impeller-Scene).

After the [migration to Flutter GPU](https://github.com/bdero/flutter_scene/issues/1) is done, a custom engine build will no longer be required.
